# Generated by Django 2.2.3 on 2019-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_voter_id', models.CharField(default='00', max_length=25)),
                ('county_voter_id', models.CharField(default='00', max_length=25)),
                ('f_name', models.CharField(default='00', max_length=30)),
                ('m_name', models.CharField(default='00', max_length=30)),
                ('l_name', models.CharField(default='00', max_length=30)),
                ('name_suffix', models.CharField(default='00', max_length=10)),
                ('birthdate', models.CharField(default='00', max_length=15)),
                ('gender', models.CharField(default='00', max_length=2)),
                ('st_num', models.CharField(default='00', max_length=15)),
                ('st_frac', models.CharField(default='00', max_length=10)),
                ('st_name', models.CharField(default='00', max_length=50)),
                ('st_type', models.CharField(default='00', max_length=20)),
                ('unit_type', models.CharField(default='00', max_length=15)),
                ('st_post_direction', models.CharField(default='00', max_length=5)),
                ('st_pre_direction', models.CharField(default='00', max_length=5)),
                ('unit_num', models.CharField(default='00', max_length=15)),
                ('city', models.CharField(default='00', max_length=30)),
                ('state', models.CharField(default='00', max_length=5)),
                ('zip_code', models.CharField(default='00', max_length=10)),
                ('county_code', models.CharField(default='00', max_length=20)),
                ('precinct_code', models.CharField(default='00', max_length=20)),
                ('precinct_part', models.CharField(default='00', max_length=20)),
                ('legislative_district', models.CharField(default='00', max_length=10)),
                ('congressional_district', models.CharField(default='00', max_length=10)),
                ('registration_date', models.CharField(default='00', max_length=15)),
                ('absentee_type', models.CharField(default='00', max_length=5)),
                ('last_voted', models.CharField(default='00', max_length=15)),
                ('status_code', models.CharField(default='00', max_length=10)),
            ],
        ),
    ]
