# Generated by Django 2.2.3 on 2019-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='absentee_type',
            field=models.CharField(default='00', max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(default='00', max_length=5),
        ),
        migrations.AlterField(
            model_name='voter',
            name='state',
            field=models.CharField(default='00', max_length=10),
        ),
    ]
