# Generated by Django 2.2.3 on 2019-07-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0003_vote_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(default='00', max_length=10)),
                ('election_date', models.CharField(default='00', max_length=15)),
            ],
        ),
    ]
