# Generated by Django 2.2.3 on 2019-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0004_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='County_Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(default='00', max_length=10)),
                ('max_votes', models.IntegerField()),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
                ('six', models.IntegerField()),
                ('seven', models.IntegerField()),
            ],
        ),
    ]
