# Generated by Django 2.2.3 on 2019-07-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0005_county_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='county_votes',
            name='zero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
