# Generated by Django 2.2.3 on 2019-07-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0007_remove_county_votes_max_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='00', max_length=30)),
                ('zero', models.IntegerField()),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('three', models.IntegerField()),
                ('four', models.IntegerField()),
                ('five', models.IntegerField()),
                ('six', models.IntegerField()),
                ('seven', models.IntegerField()),
            ],
        ),
    ]
