# Generated by Django 2.2.3 on 2019-07-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0008_city_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_votes',
            name='eight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
