# Generated by Django 2.2.3 on 2019-07-13 16:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0009_city_votes_eight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_code', models.CharField(default='00', max_length=10)),
                ('city', models.CharField(default='00', max_length=30)),
                ('voting_freq', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=10)),
                ('age_group', models.CharField(default='00', max_length=20)),
            ],
        ),
    ]
