# Generated by Django 2.2.3 on 2019-07-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0010_voting_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_voter_id', models.CharField(default='00', max_length=25)),
                ('f_name', models.CharField(default='00', max_length=30)),
                ('l_name', models.CharField(default='00', max_length=30)),
                ('birthdate', models.CharField(default='00', max_length=15)),
                ('address', models.CharField(default='00', max_length=70)),
                ('city', models.CharField(default='00', max_length=30)),
                ('county_code', models.CharField(default='00', max_length=20)),
                ('age_group', models.CharField(default='00', max_length=20)),
            ],
        ),
    ]
