# Generated by Django 2.2.3 on 2019-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0011_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
