# Generated by Django 2.2.3 on 2019-07-23 17:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0012_voter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='has_voting_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='voting_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
        ),
    ]
