# Generated by Django 2.2.3 on 2019-07-23 17:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivote', '0013_auto_20190723_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='voting_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
    ]
